### ISSUE TITLE
Support Docker CMD

### ISSUE THREAD

**Issue by piranna** [tailhook/vagga#102]
Docker execution has two execution parameters, [ENTRYPOINT](https://docs.docker.com/reference/builder/#entrypoint) and [CMD](https://docs.docker.com/reference/builder/#cmd). `ENTRYPOINT` tells what binary should be executed when the container is started, similar to vagga `run` command parameter. On the other hand, `CMD` can be used to define some default parameters that will be given to `ENTRYPOINT` if this last one is defined, so since `ENTRYPOINT` (and `run`) works like a PID 1 process inside the container, people can set `CMD` to the binary they want to execute by default, so they can easily override it when executing the container and start a shell or other thing setting it as parameters.

The question is, how can someone mimic this behaviour in vagga? How can I be able to define some default command execution arguments in vagga that can be overriden when executing a command on it? I know there's the [accepts-arguments](http://vagga.readthedocs.org/en/latest/commands.html#opt-accepts-arguments) options, but it doesn't give too much info about how to use it nor if it accepts to define default arguments... :-/

**Comment by tailhook** [comment]
1. We have docker-like:
```
vagga _run container-name command
```
This is just analog to `docker run` (without an entry point). This is only used for debugging or one-time ad-hoc command (like `sphinx-quickstart` which is run at the start of the project)

2. We have two kinds of commands, shell command:
```
run: "something"
```
And non-shell command:
```
whatever: !Command
  run: ["/usr/bin/python", "-m", "whatever"]
```

Non-shell command allows arguments by default. So when you run:
```
vagga whatever -x -y
```
Vagga runs:
```
python -m whatever -x -y
```

For shell commands you may set ``accepts-arguments: true``. Which will allow to use arguments in the shell. I.e. it's run by:
```
/bin/sh -c "something" -- -x -y
```
In the script you can use `$1`, `$2` and so on for example:
```
compile: !Command
  run: |
    input="$1"
    if [ -z "$input" ]; do
      echo "Usage: vagga compile INPUT [ OUTPUT ] [OPTIONS...]"
      exit 2
    fi
    output="${2:-default.output.out}"
    shift; shift
    exec run-compiler -i $input -o $output "$@"
```

The ``/bin/sh`` is kinda entrypoint for the container. It used to be customized in vagga 0.1. But it wasn't largely useful. As you can always just put command line directly:
```
run: !Command
  run:
  - /usr/bin/node
  - -e
  - |
     require('something')
     console.log("nodejs script")
```

In the current vagga testing you can use ``&achors`` and ``*aliases`` to make code more DRY.

At the end of the day, parsing arguments is a complex job, and I don't see the reason to reimplement another argument parser. The target application should parse arguments. And for cases where it's not YAML is good enough for placing small pieces of shell script inside.

**Comment by piranna** [comment]
Ok, now I see the point, the `CMD` behaviour can be delegated to a script that define itself the default values, so vagga doesn't need to implement that feature, good trick. Probably I was thinking too much how Docker do it... You should add that info on the docs ;-) Also, according to this, I think shell-mode could be deprecated, because except for one-liners you can do the same in a cleaner way using an external script file, isn't it?

**Comment by tailhook** [comment]
> You should add that info on the docs ;-) 

Pull requests are welcome. I'm not sure where to place it and what wording would be the most meaningful.

> Also, according to this, I think shell-mode could be deprecated, because except for one-liners you can do the same in a cleaner way using an external script file, isn't it?

Sure. But usually, I'm too lazy to put 3-4-5 line script into external file. I mean it's a matter of taste, so I'm in doubt that it should be deprecated.

**Comment by tailhook** [comment]
Well, I don't think there is something actionable left here.

**Comment by piranna** [comment]
:+1:
