### ISSUE TITLE
Allow to mount partition images / devices as volumes

### ISSUE THREAD

**Issue by piranna** [tailhook/vagga#103]
Currently vagga only support the [Tmpfs](http://vagga.readthedocs.org/en/latest/volumes.html#volume-Tmpfs), [VaggaBin](http://vagga.readthedocs.org/en/latest/volumes.html#volume-VaggaBin) and [BindRW](http://vagga.readthedocs.org/en/latest/volumes.html#volume-BindRW) volume types. I propose to create a new `Mount` one that allow to mount a new filesystem from a system device (located at `/dev`) or from a filesystem image. The parameters like filesystem type, flags or mount options would be the same ones of the `mount` command.

**Comment by tailhook** [comment]
As I've mentioned in #98, it's not possible in user namespaces.

**Comment by piranna** [comment]
According to http://unix.stackexchange.com/a/96643, in fact namespaces would be the ideal tool to allow to mount filesystems by regular users, both when initializing a vagga container or from inside it...

**Comment by tailhook** [comment]
That explanation is a little bit vague. Here is a better explanation (and an example of patch to enable a specific filesystem in user namespaces):
http://people.canonical.com/~apw/lp1377025-utopic/0001-UBUNTU-SAUCE-Overlayfs-allow-unprivileged-mounts.patch

**Comment by piranna** [comment]
> That explanation is a little bit vague

I agree, this topic needs more investigation, but seems feasable.


> Here is a better explanation

> We refuse unprivileged mounting of most filesystem types because we do not trust the in-kernel superblock parsers to correctly handle malicious input.

Interesting... that's a good reason to don't enable it, maybe it's the reason why they have delayed it so much time needing to patch all the filesystems on the kernel?


> and an example of patch to enable a specific filesystem in user namespaces

```diff
Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>
Signed-off-by: Tim Gardner <tim.gardner@canonical.com>
Signed-off-by: Andy Whitcroft <apw@canonical.com>
---
 fs/overlayfs/super.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/fs/overlayfs/super.c b/fs/overlayfs/super.c
index 9473e79..50890c2 100644
--- a/fs/overlayfs/super.c
+++ b/fs/overlayfs/super.c
@@ -668,6 +668,7 @@ static struct file_system_type ovl_fs_type = {
 	.name		= "overlayfs",
 	.mount		= ovl_mount,
 	.kill_sb	= kill_anon_super,
+	.fs_flags	= FS_USERNS_MOUNT,
 };
 MODULE_ALIAS_FS("overlayfs");
 
-- 
```

So... just a flag? Is this the only needed thing to enable OverlayFS support on namespaces? whoa... :-D

**Comment by tailhook** [comment]
Well, unfortunately we can't do anything. This is a kernel issue.
