### ISSUE TITLE
Documentation needs little fixes

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#111]
In `Configuration` you have `Commands` at the top and again `Commands` at the bottom.
Also, in `What's Special With Pid 1?`, I think `I may look like the most disruping one is first.` could have a better phrasing.

I know I could fix it myself but I observed that you are very fast with fixes, so this seems easier :)

**Comment by tailhook** [comment]
Made few adjustments. Feel free to make a pull request, if something is far from perfect :)

**Comment by lilianmoraru** [comment]
Well, just what I was saying, I barely got to shut down my PC after opening the issue...
Also, proper fixing, I would of modified just a little bit... Thanks
