### ISSUE TITLE
can vagga be installed without sudo?

### ISSUE THREAD

**Issue by satra** [tailhook/vagga#119]
i downloaded the binary and installed to a local directory. 

```
DESTDIR=/path/to PREFIX=0.4.1 install.sh
```

it installed and didn't complain about anything.

for testing i decided to build vagga itself and i get this:

```bash
$ vagga make-release
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Error running `id --user --name`: 
Error waiting for child: No child process (os error 10)"', src/libcore/result.rs:736
```

**Comment by tailhook** [comment]
Yes. You can run vagga from any dir, actualy you don't have to install just unpack the archive and run. And it needs the `id` command. The error is weird though. It seems the command works, but wait syscall is broken. Can you run with `RUST_LOG=debug`?

**Comment by satra** [comment]
nodes running on CentOS 6.5

```bash
$ RUST_LOG=debug vagga make-release
INFO:vagga::process_util: Running <Command "/usr/bin/id" "--user" "--name">
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Error running `id --user --name`: 
Error waiting for child: No child process (os error 10)"', src/libcore/result.rs:736
$ which id
/usr/bin/id
$ id --user --name
satra
```

**Comment by tailhook** [comment]
Hm. I still don't understand how is it possible :)

Could you run `strace -f -s 1000 -o strace.log vagga make-release`  and show me the `strace.log`? Since it fails early strace output should not be too large.

**Comment by satra** [comment]
here you go:

https://www.dropbox.com/s/ggko6d5zap4k3jz/strace.log?dl=0

**Comment by satra** [comment]
@tailhook - thanks for the fix. is there a place where there is an automated latest build that i can download?

**Comment by tailhook** [comment]
Yes. vagga-testing repository. It's not up to date yet (may be in a hour or few). You need at least version v0.4.1-11-gab9d3ff.

**Comment by satra** [comment]
thanks - that's what i checked. will check back later.

**Comment by tailhook** [comment]
Done. Also please say your uname -a (i.e. the kernel version)

**Comment by satra** [comment]
Linux node001 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tailhook** [comment]
Hm. As I expected. It's fine that I've fixed a bug in unshare crate that can be used for more than containerization :) But you can't use vagga. It requires kernel at least 3.8 for user namespaces.

**Comment by satra** [comment]
@tailhook - thanks for that. i just initiated the conversation to upgrade to centos7 which would have 3.10.
