### ISSUE TITLE
"/bin/sh -c" wrongly is used with "--"

### ISSUE THREAD

**Issue by KampfCaspar** [tailhook/vagga#139]
As I see it, a defined command accepting further arguments is run as

    /bin/sh -c COMMAND -- ARGUMENTS

However, the double dash is NOT used as a differentiator between sh options and COMMAND options. After the option '-c' sh does not interpret any more arguments and EVERYTHING (including the double dash) is given to COMMAND. Now, if the COMMAND accepts options but sees the double dash, options in ARGUMENTS are not recognized anymore.

/bin/sh should be called without the double dash, if I understand the situation correctly. ARGUMENTS may not contain sh options as '-c' ends option interpretation in and of itself.

**Comment by tailhook** [comment]
The use case of `--` is to make `$1` the first argument that is passed to the script, otherwise you will have first argument as `$0` and `$@` and `$*` skip one of the arguments.

Do you have some use case that doesn't work well?

**Comment by KampfCaspar** [comment]
My bad, I mentally mixed two concepts: the 'run' entry defining an executable to run vs. a command line to interpret. Both are possible as per the documentation:

    /bin/sh -c 'COMMAND ARGUMENTS'

vs.

    /bin/sh -c COMMAND -- ARGUMENTS

I originally expected the ARGUMENTS simply to be given to COMMAND (the first), while the actual calling pattern (the second) offers up the ARGUMENTS to the command line without automatically appending it. Of course, it's possible to emulate the first by appending "$@" to the COMMAND (and you're correct that the double dash is useful in this case).

Upon revisiting the documentation, I recognize there is a distinction of shell commands (string) and 'regular commands' (list). The second one's behaviour (even if it does not involve the shell) is what I originally expected...

Might it be possible to clarify the documentation as e.g. per #140 ?

**Comment by tailhook** [comment]
Sure. Documentation clarifications are always welcome. #140 is merged.
