### ISSUE TITLE
running vagga on a vanilla CentOS 7.2 system

### ISSUE THREAD

**Issue by satra** [tailhook/vagga#147]
i'm trying to run vagga on a vanilla CentOS 7.2 system as a user. it immediately errored about missing /etc/subuid . from the documentation it appears i'm missing a few things. so i can ask my sysadmin to install the shadow package (is that the correct package on centos 7.2). i am also a little confused about what the sysadmin needs to do after that to allow every user to run vagga. it seems that every user has to be added to the /etc/subuid file.

has anyone worked out a step by step install on a centos/rhel platform? 

my system is running (3.10.0-229.el7.x86_64), which should have namespace support.

**Comment by tailhook** [comment]
I don't run CentOS, so my answer is a bit theoretical.

Recent `adduser` has the settings (http://man7.org/linux/man-pages/man5/login.defs.5.html):
```
       SUB_GID_MIN (number), SUB_GID_MAX (number), SUB_GID_COUNT (number)
           If /etc/subuid exists, the commands useradd and newusers (unless
           the user already have subordinate group IDs) allocate
           SUB_GID_COUNT unused group IDs from the range SUB_GID_MIN to
           SUB_GID_MAX for each new user.

           The default values for SUB_GID_MIN, SUB_GID_MAX, SUB_GID_COUNT
           are respectively 100000, 600100000 and 10000.

       SUB_UID_MIN (number), SUB_UID_MAX (number), SUB_UID_COUNT (number)
           If /etc/subuid exists, the commands useradd and newusers (unless
           the user already have subordinate user IDs) allocate
           SUB_UID_COUNT unused user IDs from the range SUB_UID_MIN to
           SUB_UID_MAX for each new user.

           The default values for SUB_UID_MIN, SUB_UID_MAX, SUB_UID_COUNT
           are respectively 100000, 600100000 and 10000.
```
In Ubuntu default SUB_UID_COUNT and SUB_GID_COUNT are 65536, and it's value vagga works the best. 

If this is configured, the `useradd` commands populates `subuid`/`subgid` files automatically. But for old users, yes, you need to add each one manually.

As far as I can find, centos does not have `shadow` package, and `shadow-utils-4.1.5.1-18` package (which seems latest version in centos 7.2) does not contain `newuidmap/newgidmap`. You need shadow of at least 4.2. I'm not sure what you can do, except compile it from sources. Is there any "updates" repository, or can you download rpm from somewhere?

Sorry, that I can't be more helpful.

**Comment by satra** [comment]
thanks @tailhook - i found this which may get me there.

https://it-offshore.co.uk/linux/CentOS/29-CentOS-7-unprivileged-lxc-containers
