### ISSUE TITLE
Get rid of PathExt

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#154]
It's already in std::path::Path in rust 1.5

**Comment by srinivasreddy** [comment]
Looks like Rust guys deprecated PathExt,  advised to use std::fs::metadata instead. Do you have any plans around that?

**Comment by tailhook** [comment]
1. Rust never had `PathExt` in stable rust. So vagga doesn't use it. There is our own `PathExt` in `src/path_util.rs`
2. Most methods that was on unstable `PathExt` (and that are on our `path_util::PathExt`) are actually stabilized in new rust on `Path` type directly without an extension trait (`exists()`, `is_dir()`, ..etc)

So the issue stays the same. We still looking for a volunteer to do the work.

**Comment by srinivasreddy** [comment]
@tailhook Please close this isse

**Comment by tailhook** [comment]
Yup. Closed in #198
