### ISSUE TITLE
_create_netns failing

### ISSUE THREAD

**Issue by livioribeiro** [tailhook/vagga#167]
I'm running a freshly installed Xubuntu 15.10 `Linux 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 GNU/Linux`

I tried to run the flaky-network example, then when I ran `vagga _create_netns` it failed with the following output:

```
net.ipv4.ip_forward = 1
net.ipv4.conf.vagga.route_localnet = 1
modprobe: ERROR: could not insert 'ip_tables': Operation not permitted
iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
ERROR:vagga::setup_netns: Error running command <Command "/sbin/iptables" "-t" "nat" "-A" "POSTROUTING" "-o" "vagga_guest" "-j" "MASQUERADE"; environ: {"TERM"="xterm","PATH"="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games","RUST_LOG"="warn",}>: exited with code 3
vagga_setup_netns exited with code 1
```

Running `sudo iptables -t nat -L` shows that no iptables rule was added, so I added the rule manually, then ran `vagga run-normal` but I was unable to view the page at http://172.18.255.2:8000.

Trying `traceroute 172.18.255.2` shows that it tries to route to my local network, which means that the routing was not setup by `vagga _create_netns`.

Networking between containers seems to work since I tried a django + postgres setup and the two containers were able to talk to each other.

**Comment by tailhook** [comment]
Hm, it looks like iptables in a container needs a module, but has no permissions to insert a module from the container.

Your problem should go away if you run:
```
vagga _destroy_netns
vagga _create_netns
```
(since it seems you manually loaded the module)

If that helps, I'll try to work out some right combination of commands to make it running on the pristine system (i.e. trigger module loading from host system rather than a container).

**Comment by livioribeiro** [comment]
Running this:
```
vagga _destroy_netns
vagga _create_netns
```
didn't show any error, but still I can't access the example

**Comment by tailhook** [comment]
Hm. I've just had the same problem, but then noticed that I have a VPN for the same network. After disabling VPN network works.

> Trying traceroute 172.18.255.2 shows that it tries to route to my local network, which means that the routing was not setup by vagga _create_netns.

Probably you have a same problem if you have some network that occupies `172.18`, it won't work. I've planned to make it configurable some day, but may be I need to pick a better default network :)

**Comment by livioribeiro** [comment]
Well, this is strange, I was running a freshly installed VM.

I will see if I can figure out the problem.

Thanks!

**Comment by tailhook** [comment]
Could you show the routing table ( `ip route` ) and `iptables` output? If it's some default configuration of some VM setup, it would be good to know.

**Comment by livioribeiro** [comment]
```
$ ip route
default via 10.0.2.2 dev enp0s3  proto static  metric 100 
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15  metric 100 
169.254.0.0/16 dev enp0s3  scope link  metric 1000

$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

$ sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.18.255.0/30      anywhere
```

**Comment by livioribeiro** [comment]
I managed to make it work in my django + postgres project, I just ran
```
sudo ip link set vagga up
```
But the flaky-network example still doesn't work

**Comment by tailhook** [comment]
Hm that is interesting. Also, how do you access the http://172.18.255.2:8000 address? It's only available in the VM itself not from the outside of the VM (where I usually run a browser).

I can add the line above to the vagga commands, but can you show the output of `ip addr` just after `vagga _create_netns` ? I have something like this:
```
29: vagga@if30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 36:e7:d0:80:28:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.255.1/30 scope global vagga
       valid_lft forever preferred_lft forever
    inet 169.254.132.71/16 brd 169.254.255.255 scope global vagga
       valid_lft forever preferred_lft forever
    inet6 fe80::34e7:d0ff:fe80:28e9/64 scope link 
       valid_lft forever preferred_lft forever
```
Which shows that interface is up.  But I also see the zeroconf IP here, may be some other utility enables the interface for me and assigns random zeroconf address.

And what's wrong with flaky-network example? Can't you access the server? Or doesn't it stop the network periodically? (it should drop all the packets each other second, so you get sometimes working sometimes slow/non-working connections)

**Comment by livioribeiro** [comment]
I'm trying to access http://172.18.255.2:8000 from inside the VM and firefox simply keeps waiting for the connection to be established.

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:76:0c:e6 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 85973sec preferred_lft 85973sec
    inet6 fe80::a00:27ff:fe76:ce6/64 scope link 
       valid_lft forever preferred_lft forever
3: vagga@if4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether e6:c5:53:fc:86:ae brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.255.1/30 scope global vagga
       valid_lft forever preferred_lft forever
```

**Comment by livioribeiro** [comment]
Something interesting: When docker is installed, the networking works in vagga.

In my VM where the networking was working, docker was also intalled, but not in the VM where I tested the example, so I just installed docker, ran `sudo ip link set vagga up` and it worked.

Maybe docker does something during installation that vagga also needs?

**Comment by tailhook** [comment]
Yes. It looks like I have a DHCP server that enables an interface for me.
Fixed in v0.4.1-119-g315fe00 could you try if it works for you (already in testing)?

**Comment by livioribeiro** [comment]
It worked!

Thanks a lot!

**Comment by tailhook** [comment]
Thank you for help!
