### ISSUE TITLE
Additions to PATH

### ISSUE THREAD

**Issue by andreaferretti** [tailhook/vagga#172]
Is there a way to add entries to `$PATH`? I see there are various ways to add environment variables, but `$PATH` cannot be replaced entirely, one usually adds to it

**Comment by tailhook** [comment]
It's intentionally done in this way. While there is default path, for simple cases, vagga does not consult `/etc/environment`, `/etc/profile.d`, `$HOME/.bashrc` and all other places.

This is done so you explicitly specify a PATH and a whole environment for your application **explicitly**, so when you start the container in production you can see what exact environment the application requires.

So yes, just write the whole PATH with additional things in the config. You can also manipulate the environment in a shell script if you wish. But latter should only be used for ad-hoc development scripts.

**Comment by andreaferretti** [comment]
Thank you, I am doing with the whole $PATH and seems fine so far
