### ISSUE TITLE
More recent version published

### ISSUE THREAD

**Issue by andreaferretti** [tailhook/vagga#173]
I see that a few commands, such as `!Download` and `!Remove` are mentioned in the documentation, but are not available for version 0.4.1. It would be nice if you could release a newer version that includes the latest commands.

One can certainly do without and use the shell, but they make the structure of containers more clear

**Comment by tailhook** [comment]
Well, yeah, the 0.4.2 is waiting for #152 for too long probably. I'll either fix it or defer to the next version in the next few days.

In the meantime, it seems everybody uses vagga-testing repo, which is built directly from master. I'm trying to keep it working at all times (at least, it doesn't deploy if unit tests fail)

**Comment by andreaferretti** [comment]
Thank you, I tried vagga-testing, works great for me! You're really helping out a lot! :-)

**Comment by andreaferretti** [comment]
Any news on publishing version 0.4.2? The vagrant plugin requires the latest version installed, and so it is stuck on 0.4.1

**Comment by tailhook** [comment]
Yeah, I still want to do that in the nearest future. Just don't have enough time to do all the preparations...

You can probably ask @rrader to make an option to use `vagga-testing` in the vagrant-vagga
