### ISSUE TITLE
Probably dependance on CONFIG_USER_NS should be mentioned upfront in README

### ISSUE THREAD

**Issue by vi** [tailhook/vagga#179]
> Vagga is different as it uses a user namespaces

That may be stopper for some scenarios, especially involving outdated setups.

Probably deserves mention in README and also on [homepage](https://vagga.readthedocs.org/en/latest/).

**Comment by tailhook** [comment]
@vi I think for people who knows what CONFIG_USER_NS is, mentioning "user namespaces" everywhere is good enough. Also, there is a patched CONFIG_USER_NS in some distributions, so it wouldn't be much more clear.

In installation guide there are more details. So I'm in doubt I can do something more helpful.

Anyway, pull requests are appreciated.

**Comment by vi** [comment]
But I don't see the word "namespace" in README at all.

Homepage mentions only "linux namespaces", of which user namespace is relatively new addition.

**Comment by tailhook** [comment]
> Fully userspace containers

 Not clear enough? What spelling would be good?

**Comment by vi** [comment]
From this phrase I have deduced that it may rely on CLONE_NEWUSER (although it can also be done with ptrace or enumation).

Maybe more explicit would be better. Additionally it would bring vagga to search results for programs using user namespaces.

**Comment by tailhook** [comment]
Since even Archlinux now has CLONE_NEWUSER enabled, is it still useful?

**Comment by vi** [comment]
@tailhook , Archlinux is a quick-moving distro which is supposed to follow fresh new trends.

Better consider "Since even stable Red Hat, Slackware and old hat sysadms who are wary of new things (especially security-sensitive) do enable CLONE_NEWUSER by default," as a reason not to specify it.

CLONE_NEWUSER exposes a lot code paths in kernel which were previously accessible only to root. It means it may stay disabled like many other new things.

**Comment by tailhook** [comment]
We know it works on debian, ubuntu, archlinux, opensuse

From what I [observe](https://bugzilla.redhat.com/show_bug.cgi?id=1295287) it works on fedora but not on rhel.

Also, remember we're talking about desktop and CI systems, not servers (nobody runs vagga on servers). And vagga relies on all other kernel flags (like other namespaces, cgroups ...), so it's strange idea to enumerate them all on the front page.

And given that nobody bothered to make a PR in two years, I'm going to close this.

**Comment by tailhook** [comment]
Slackware [looks like](ftp://ftp.osuosl.org/pub/slackware/slackware64-14.2/ChangeLog.txt) having it enabled too (not sure this is a trusted source though).
