### ISSUE TITLE
Usage on OSX

### ISSUE THREAD

**Issue by andreaferretti** [tailhook/vagga#183]
While I work on Ubuntu, most of my colleagues use OSX. On Docker, there is docker-machine which allows to use docker in a VM rather transparently. Is there anything like that for Vagga? If not, is there any example of, say, a working vagrant configuration or something like that which could allow oSX users to run vagga?

I am not very familiar with Vagrant. I guess a basic example could be easy to setup, but one needs to take into account sharing of the work folder with proper user permissions, networks sharing and so on, so that everything works as smoothly as with vagga.

**Comment by lilianmoraru** [comment]
@andreaferretti Vagga is a Linux only software.
It uses some Linux kernel specific features(same story with Docker, although Docker over time created tools to power up VMs and run Linux inside them).

To be able to use Vagga they need to start a VM with Linux, through any method they want(Vagrant, VirtualBox + Linux image, VMWare Player + Linux image...).
A relatively modern Linux kernel is needed. For example it works with Ubuntu 12.04 LTS(almost 4 years).

Sadly, I am not familiar with Vagrant myself.
The main maintainer is currently on vacation, he might have some other suggestions...

**Comment by tailhook** [comment]
@andreaferretti, you may try https://github.com/rrader/vagrant-vagga . I'm not sure you can use it as easy as a vagga on linux. (it creates a virtual machine, you need to shutdown it at some time, running vagga in multiple projects requires multiple virtual machines AFAIR, and so on). 

Anyway, I may put some example Vagrantfile in the documentation. Is it something you are asking for?

**Comment by andreaferretti** [comment]
@tailhook Thank you, this is exactly what I had in mind! I have an example Vagrantfile [here](https://github.com/andreaferretti/vagga-examples/blob/master/vagrant/Vagrantfile) but it works so so.

I think the plugin you linked is exactly what my colleagues need! Thank you again for your quick help! :-)
