### ISSUE TITLE
inherit-environ command config option doesn't appear to be wired up

### ISSUE THREAD

**Issue by cablehead** [tailhook/vagga#19]
Not sure if I'm missing something?

**Comment by tailhook** [comment]
Yes. I thought it was a good idea. But I'm not sure now. It may have security implications. I.e. if user have amazon keys in his environment, they may be used by contained program. So it's kinda both feature and security hole.

Currently we have `VAGGAENV_XXX` environment variables that are propagated with prefix stripped. And `-e` flag directly on command-line. Do you have any use case that is solved with these instruments in some ugly way?

**Comment by cablehead** [comment]
VAGGAENV_XXX will do just what I need. Thanks Paul.

**Comment by tailhook** [comment]
Should be fixed in docs. And also probably a FAQ entry?

**Comment by cablehead** [comment]
I can do that this weekend. Unless you're already working on it?

**Comment by tailhook** [comment]
Not yet. Would be nice if you do.

**Comment by tailhook** [comment]
Merged in #20
