### ISSUE TITLE
Support for Ubuntu i386 installations

### ISSUE THREAD

**Issue by jpiles** [tailhook/vagga#191]
Since one of the use cases of vagga is to replicate older systems, is it possible to do a 32bit installation, as opposed to a 64bit / multilib one in Ubuntu?

**Comment by tailhook** [comment]
I have never tried, but it should be possible. You can try it using [!Tar](http://vagga.readthedocs.org/en/latest/build_steps.html#step-Tar) and `!Sh` commands. If that works fine, we can probably extend `UbuntuRelease` command to handle 32bit installation too

**Comment by jpiles** [comment]
I was just skimming the code source, and I see [here](https://github.com/tailhook/vagga/blob/master/src/builder/commands/ubuntu.rs#L298) that there is a variable to choose the arch when retrieving the proper ISO. I don't know rust too well, but would it be possible to just override it with some configuration parameter?

Anyway, I'll try the !Tar way to see if it works (I don't see why it shouldn't, though)!

**Comment by tailhook** [comment]
No, without changing code. Parameter must be added here https://github.com/tailhook/vagga/blob/master/src/config/builders.rs#L67 and then it may be used in the code doing image download.

**Comment by jpiles** [comment]
Thanks for the tip! I'll try to get it working and submit a pull request then (if it works, of course)

**Comment by tailhook** [comment]
You're welcome!. You will also need to fix a [validator](https://github.com/tailhook/vagga/blob/master/src/config/builders.rs#L269)

**Comment by tailhook** [comment]
Fixed in #192
