### ISSUE TITLE
Permission Errors when cleaning up from _run --writeable

### ISSUE THREAD

**Issue by talevy** [tailhook/vagga#203]
I am seeing this error when exiting from a `_run`

```
$ vagga _run --writeable logstash bash
root@vagrant-ubuntu-vivid-64:/work# exit
ERROR:vagga::wrapper::clean: Error cleaning up: Can't remove file "/var/cache/apt/archives/libkrb5support0_1.12.1+dfsg-18ubuntu0.1_amd64.deb": Permission denied (os error 13)
WARN:vagga::launcher::underscore: The `vagga _clean --transient` exited with status: Ok(3)
```

here is the container definition: https://github.com/talevy/elastic-stack-tests/blob/master/vagga.yaml#L89

should I be seeing this? am I not cleaning a certain cache correctly?

**Comment by tailhook** [comment]
Than command works for me. This is some vagrant problem. Had you done the recommended bind mount? (#53)

**Comment by talevy** [comment]
I thought I did. I will close this and investigate locally
