### ISSUE TITLE
Plz build new version for vagga-install-testing.sh

### ISSUE THREAD

**Issue by webknjaz** [tailhook/vagga#214]

**Comment by tailhook** [comment]
What's wrong with it? It's marked 0.4.1-240- but it's the same version as 0.5.0. New one will be available on the next build. Also stable version is just as up to date as the one in testing.

**Comment by tailhook** [comment]
Anyway, it's already there.

**Comment by webknjaz** [comment]
Thanks, I've just got confused with testing version lower, than stable :)
