### ISSUE TITLE
Managing dependencies with Composer

### ISSUE THREAD

**Issue by pbuyle** [tailhook/vagga#218]
When using Vagga to work on a PHP project using Composer, how is one expected to manage dependencies?

When not using Vagga, the `composer require` command can be used to download dependencies and update the `composer.json` and `composer.lock` accordingly. The user can also edit the `composer.json` file directly and then run the `composer update` command.

When using Vagga, composer is only temporarily installed during the container build. And when building the container with a `!ComposerDependencies`, the `composer install` command is used to download dependencies. If the project folder contains a `composer.lock` file (as it should once put under version control), change to the `composer.json` will be ignored during container build. And the user as now way to have additional dependencies downloaded (or existing one updated).

Is the composer support not intended to be used the manage the project's dependencies, but only those of applications? This is not what the Laravel tutorial suggest.

One option is to create a copy of the `composer` binary during container build and expose it as a command. But since downloaded dependencies are stored in the immutable container (in `/usr/local/lib/composer/vendor`), it can not be used to update them.

Another option would be to not use Vagga composer support but install and then use composer on my own. Sadly, it means it can't re-use Vagga cache directory as they are not exposed to commands.

A third option would be to delete the `composer.lock` file when dependencies are changed, but this seems counter intuitive to composer users.

What would be the recommended way a manage my project dependencies with Composer?

**Comment by tailhook** [comment]
Well, there is no yet builtin way to do that task, and we are discussing some of them in #114, and #135.

There are couple of ways to do it in more ad-hoc way. Like this:
```
vagga _run -W mycontainer bash
$ .. do install composer again
$ composer require ..
```
This is probably not very convenient because that "do install composer" step has about three bash commands or something like that.

One option to fix this is to have an option to keep "composer" in the container. But this means bigger containers in the result. I like it to keep them as clean as possible

May be we can make a separate vagga command like:
```
vagga _update --tool composer --run composer require ...
```
This is an alternative to #114 and #135 which are probably too much focused on how python tools work.

Ping @livioribeiro who contributed the PHP support.

**Comment by pbuyle** [comment]
When working with Composer as dependencies manager for the project, having it in a container make sense. IMHO, managing a project's dependencies is on ongoing process, it can't be restricted to a build phase. The used tool need to be available to the user. I can understand why some user may not care for a dependencies management tool. For instance, when used to download the dependencies of an installed application. But other users may want to be able to, efficiently, use it.

An alternative solution may be to have options to
- Keep Composer (or any packages manager) installed once the container is build. Off course, this would also keep the needed environment variables.
- Allow Composer vendor directory (or any packages manager download directory) to be configured.
- Allow caches to be used during both build and command execution.

That way, one can keep Composer available in a container, store the managed dependencies somewhere in `/work` (likely `/work/vendor`) and use it from commands. And when used from a command, Composer uses the same environment variables that when building the container. Which means it would use the configured vendor and cache directories. With this, one can configure a `composer` command and run both `composer require` and `composer update` safely.

Side note: Since a `composer.json` has not effect on the result of a `composer install` once the `composer.lock` file exists, updating `composer.json`should not trigger a container rebuild when `composer.lock` exists.

**Comment by livioribeiro** [comment]
When I started the work with php and composer, I initially thought of installing dependencies at `/work/vendor`, but this would make one container interfere on how other containers are built and versioned, as was pointed out at https://github.com/tailhook/vagga/pull/185#issuecomment-191691038.

Adding options to keep composer binary after container build and change vendor directory are easy tasks.

Allowing caches to be used after container is built is beyond the php integration.

**Comment by pbuyle** [comment]
I understand the reasoning for not using `/work/vendor` as default vendor dir. My suggestion is not the change the default behavior, but rather to provide an alternative vendor directory as an option. Likely, if two containers are using different Composer dependencies, you need two `composer.json` files. So it would seems logical that, in this case, you would also want two `vendor` directories alongside your two `composer.json` file.

I understand that cache usage after container is build to is beyond the php integration, but I wonder if other use case could benefit from it. If other dependencies manager are allowed to be kept, the need to share their cache with commands will also be there. Like for the vendor directory, the proposition would be for this to be optional. Allowing cache directories to added as volumes may be one way to solve this.

**Comment by tailhook** [comment]
> I understand the reasoning for not using /work/vendor as default vendor dir. My suggestion is not the change the default behavior, but rather to provide an alternative vendor directory as an option. Likely, if two containers are using different Composer dependencies, you need two composer.json files. So it would seems logical that, in this case, you would also want two vendor directories alongside your two composer.json file.

You just probably need two different containers.

> I understand that cache usage after container is build to is beyond the php integration, but I wonder if other use case could benefit from it. If other dependencies manager are allowed to be kept, the need to share their cache with commands will also be there. Like for the vendor directory, the proposition would be for this to be optional. Allowing cache directories to added as volumes may be one way to solve this.

Yes, I plan to add the feature but for very different reason.

On the other points, I'm still thinking of it. So expect a more thoughtful response soon.

**Comment by livioribeiro** [comment]
@tailhook If you're ok with it, I can start working on adding the options to keep composer binary and change vendor directory.

**Comment by tailhook** [comment]
@lilianmoraru I'm fine with the options. It just doesn't solve @pbuyle's issue.

**Comment by pbuyle** [comment]
Being able to put the vendor directory in `/work` and keeping Composer installed after build solve most of the issue. It will allow me to manage dependencies on a built container, using commands.

What will be missing is a (safe) way to re-use the cache directory.

**Comment by tailhook** [comment]
Okay, let me try to explain

> When working with Composer as dependencies manager for the project, having it in a container make sense. IMHO, managing a project's dependencies is on ongoing process, it can't be restricted to a build phase. 

While I agree that project dependencies are ongoing process, the containers are not carved in stone too. Here [is an article](https://medium.com/@paulcolomiets/vagga-the-higher-level-package-manager-e49e85fed42a) that covers ideas, I think. But I'll try to give you a smaller summary.

1. When you change dependencies it's fine that container is rebuilt. We have all kinds of caches to make it faster.
2. When you pull the project vagga, evaluates the dependencies, and decides whether a container needs to be rebuilt (if dependencies change)
3. The process creates a new container for each combination of dependencies. They are hidden somewhere in `.vagga` subdirectory.
4. When you switch between branches, already built containers are reused. So switching the branch is instant
5. When you done with branches you do `vagga _clean --unused` to remove unused versions of containers.

When you have `vendor` folder in the `/work` you can't have all these features. Moreover, you risk to run the project with wrong dependencies, because you have forgotten to run `composer update`. This is a specific error that vagga tries to fix on your behalf.

Is it more clear now?

I know this doesn't fully solve the issue for you. But to find out nice and clear solution you need to wrap around the vagga concepts and not to think of vagga as anything similar to virtual machines or alike.

**Comment by pbuyle** [comment]
If I understand correctly, then the best way to handle Composer would be to simply don't use `composer require` or `composer update` but to always update `composer.json` manually and run `rm composer.lock && vagga _build <container>` when I would normally run `composer update`?

**Comment by pbuyle** [comment]
Ok, how about this.

In my container built steps, I added `!Sh cp /usr/local/bin/composer /usr/local/bin/composer.keep` to keep a copy of composer installed. Then I added a command (see code below) that allow me to use most of Composer commands. But without letting me actually download dependencies.
```
  composer: !Command
    description: Run a Composer command
    container: drupal
    run: |
      case "$1" in
      cache-clear|dump-autoload|create-project|self-update|global|install)
        echo Command not allowed: $1
        ;;
      update)
        if [ -f /work/composer.lock ]; then
          rm /work/composer.lock
        fi
        ;;
      require|remove)
        if composer.keep --no-update $@ && [ -f /work/composer.lock ]; then
          rm /work/composer.lock
        fi
        ;;
      *)
        composer.keep $@
        ;;
      esac
    accepts-arguments: true
    environ:
      COMPOSER_HOME: /tmp
      COMPOSER_ALLOW_SUPERUSER: 1
```

With this command, To add or remove dependencies, I can either use `vagga composer [require|remove]` as a replacement of `composer [require|remove]`. Or edit the `composer.json` file manually and then use `vagga composer update` as a replacement of `composer update`. In both cases, added or removed dependencies will be downloaded by Vagga on the next command run.

**Comment by tailhook** [comment]
> If I understand correctly, then the best way to handle Composer would be to simply don't use composer require or composer update but to always update composer.json manually and run rm composer.lock && vagga _build <container> when I would normally run composer update?

This is essentially what we are doing for node.js and python (which don't have automatically generated `.lock` file). So yes this good way.

I'm not sure exactly how the composer work. But the usual downside of this option is that you have to update all the dependencies at once. I.e. you can't add just one dependency and keep all other versions same as in lockfile.

As for the command: I'm not sure you can run `composer require` in such scenario (you may want to adjust [write-mode](http://vagga.readthedocs.org/en/latest/commands.html#opt-write-mode) for that). But if it works for you, it's fine. @livioribeiro will probably make an option, so you don't have to copy manually.

**Comment by tailhook** [comment]
Okay, except cache directories (#253) which have more uses than what is discussed here, I think there is nothing actionable here.
