### ISSUE TITLE
Implement shortcut for ubuntu multiverse

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#223]
This is similar to `!UbuntuUniverse`. May be we may use same shortcut for ubuntu repositories like for alpine #220. I.e.:

```
- !Ubuntu trusty
- !Repo universe
- !Repo multiverse
```
```
- !Apline v3.3
- !Repo community
- !Repo testing
```

The `!Repo` name is ugly, any better name?

**Comment by anti-social** [comment]
Good name as for me.

It is called repositories in Alpine and in Ubuntu:
https://pkgs.alpinelinux.org/packages
https://help.ubuntu.com/community/Repositories/Ubuntu

**Comment by tailhook** [comment]
Well, it lacks context. Is it git repository? Or plugin repository? Or python repository?

More options (neither to good for me):

* `Repository`
* `PackageRepo`
* `PackagesFrom`
* `InstallFrom`
* `DistributionRepo`
* `OSRepository`

Anyway we need to wait for `boxed_steps` branch to land before adding more commands.

**Comment by tailhook** [comment]
Closing in favor of #316
