### ISSUE TITLE
A very basic question

### ISSUE THREAD

**Issue by zenny** [tailhook/vagga#225]
Hi I tried to follow an example at http://www.sitepoint.com/containerized-php-development-environments-with-vagga/

Builds very fine. However, when I tried to `vagga run` after successful builds, it gives:

```
$ vagga
Available commands:
    php                 passes the given parameters to the PHP interpreter
    run                 Run the NGINX and PHP stack
$ vagga run
[18-Apr-2016 19:36:26] ERROR: No pool defined. at least one pool section must be specified in config file
[18-Apr-2016 19:36:26] ERROR: failed to post process the configuration
[18-Apr-2016 19:36:26] ERROR: FPM initialization failed
---------- Process php:3213 exited with code 78. Shutting down -----------
```

However, `vagga php -v` output is fine:

```
$ vagga php -v
PHP 7.0.5-3+donate.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Appreciate any inputs!

**Comment by tailhook** [comment]
Unfortunately, I'm not familiar with PHP. You should consult PHP/php-fpm documentation. Also pinging @livioribeiro and @parhamdoustdar if they can help.

**Comment by zenny** [comment]
@tailhook Thanks for the reply. 

However,I tried too with https://github.com/tailhook/vagga/tree/master/examples/firefox without any modifications, but getting:

`ERROR:vagga::wrapper: Error executing firefox: Can't mount bind "/volumes/X11" to "/vagga/root/tmp/.X11-unix": No such file or directory (os error 2)`

**Comment by tailhook** [comment]
Yes this is normal. To have working firefox (i.e. any x11 program) you need to configure volume in your settings:
```
external-volumes:
  X11: /tmp/.X11-unix
```
More about settings: http://vagga.readthedocs.org/en/latest/settings.html

Well, this needs to be documented somewhere...

**Comment by zenny** [comment]
Appending:

```
external-volumes:
  X11: /tmp/.X11-unix
```

output:

```
$ vagga firefox
ERROR:vagga::wrapper: Error executing firefox: Can't mount bind "/volumes/X11" to "/vagga/root/tmp/.X11-unix": No such file or directory (os error 2)
```

**Comment by tailhook** [comment]
Which file did you place "external-volumes" into?

**Comment by zenny** [comment]
> Which file did you place "external-volumes" into?

vagga.yaml (https://github.com/tailhook/vagga/blob/master/examples/firefox/vagga.yaml)

**Comment by tailhook** [comment]
You need to put it into `.vagga.yaml` into your HOME directory. (or any other location from the [documentation](http://vagga.readthedocs.org/en/latest/settings.html))

**Comment by tailhook** [comment]
I assume this is answered. Feel free to reopen.
