### ISSUE TITLE
Use ubuntu cloud images

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#230]
The `cdimage.ubuntu.com` we currently use for image downloading remove previous releases of the images. Also it seems to change folder layout after `trusty`. So we should use instead:

https://cloud-images.ubuntu.com/precise/current/

The problem is that busybox can't unpack that images:

```
tar: unknown typeflag: 0x53
```

So we should probably do #33, fix the unpacking, and then change the url.

We should also investigate, whether it changes the list of pre-installed and similar things.

**Comment by tailhook** [comment]
Okay, we've fixed the tar crate but the images described above are much bigger than what we had earlier. I.e. the ubuntu core trusty image is about 190Mb (unpacked), while the ubuntu server-cloudimg is about 460Mb.

So we are going to use an image from https://partner-images.canonical.com/, the same that docker uses for `!Ubuntu` and use same `cdimage.ubuntu.com` with fallback to `old-releases.ubuntu.com` for  the `!UbuntuRelease` command (because that requires resolving releases by number).

In the end this increases the number of ubuntu images available for use in vagga.

**Comment by tailhook** [comment]
It seems ubuntu already removed images from cdimage.ubuntu.com which indexed by version number (e.g. 16.04). Which renders !UbuntuRelease in it's current form almost useless (only able to download old releases).

Should add codename to the `!UbuntuRelease` and deprecate `version`.

**Comment by lilianmoraru** [comment]
Why useless? `!UbuntuRelease` currently supports also choosing the `arch`, no?
Or with the new changes it was set to always download `x86_64`?

**Comment by tailhook** [comment]
I mean there are no images that you can download by version. We need to add `codename` parameter to make `!UbuntuRelease` useful again (i.e. having a way to specify `arch`).

For backward compatibility we will probably map hardcode version numbers to codenames in vagga itself.

**Comment by tailhook** [comment]
Another attempt to fix `!UbuntuRelease` in d56fe3f:

1. Introduce `codename`
2. Introduce `url` for users who wish full freedom
3. Deprecate `version` and made a mapping between versions and codenames for backward compatibility.

**Comment by lilianmoraru** [comment]
Yey for `url`. Personally, I missed that.

**Comment by tailhook** [comment]
Looks like it fine now.
