### ISSUE TITLE
Py2(3)Requirements ignores included files

### ISSUE THREAD

**Issue by Orhideous** [tailhook/vagga#236]
Bug walkthrough
---------------------

Assume, we've two files:
**requirements/dev_bundle.txt**
```
-r requirements/prod.txt
dev_first==1.0.0
dev_second==1.0.0
```
**requirements/prod.txt**
```
package_a==1.2.3
```
And the relevant step in `vagga.yaml`:
```yaml
- !Py3Requirements requirements/dev_bundle.txt
```

Currently vagga ignores any changes in `requirements/prod.txt`, but it shouldn't.

Workaround
----------------
Explicit usage of `!Depends`, like this:

```yaml
- !Depends requirements/prod.txt
- !Py3Requirements requirements/dev_bundle.txt
```

**Comment by lud4ik** [comment]
Megred in master https://github.com/tailhook/vagga/pull/278
