### ISSUE TITLE
Link statically against musl libc

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#24]
Currently we kinda rely on unsupported and buggy feature of linking against glibc. Should instead link against musl libc

Some info: https://gist.github.com/cl91/bb927df2525738502131#file-static-linking-against-musl-md

**Comment by bstrie** [comment]
This is now supported in the nightly version of the Rust compiler, on an experimental basis:

https://github.com/rust-lang/rust/pull/24777

**Comment by aidanhs** [comment]
I'm curious - why do you say this is buggy?

**Comment by tailhook** [comment]
> I'm curious - why do you say this is buggy?

1. Some functions are two order of magnitude slower (e.g. clock_gettime)
2. glibc still tries to use ``*.so`` plugins even if statically built. When they are absent on system (e.g. in container), it's ok (except some function don't work). But on host system when ``.so`` plugins files are not ABI-compatible with glibc compiled into vagga, it just crashes with segmentation fault.

To name a few, just from the top of my head.

**Comment by aidanhs** [comment]
Gotcha, was aware of these, just wanted to check there are no others. Thanks :)

**Comment by tailhook** [comment]
It's done in master. Will do some testing before the release though.
