### ISSUE TITLE
Release 0.5.1 for Ubuntu images fix?

### ISSUE THREAD

**Issue by dato** [tailhook/vagga#258]
Hi—

It would be really nice to see a binary release with minimal fixes (from d56fe3fd?) applied. Unless I'm missing an alternative way, at the moment it's not possible to use vagga with Ubuntu.

**Comment by lilianmoraru** [comment]
Use `vagga-testing`, it is as stable as `vagga stable`(At least both have to pass the same suite of tests).

`curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh`

**Comment by tailhook** [comment]
Yes. We are going to release vagga 0.6 soon. In the meantime it's probably better to use testing.

**Comment by dato** [comment]
Ah, thank you! I see it’s even mentioned in the install docs, but I failed to notice it.

Thanks a lot.

**Comment by lilianmoraru** [comment]
@dato If you think there is nothing else actionable here(there are plans for vagga 0.6 to be released), please consider closing the issue.

**Comment by dato** [comment]
Absolutely. I was just deferring the decision to maintainers.

Thanks!
