### ISSUE TITLE
Alpine download URL substitution

### ISSUE THREAD

**Issue by webknjaz** [tailhook/vagga#261]
HTTP request to `http://dl-6.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz` returns `500 - Internal Server Error`

Is there any way to work around this?

**Comment by tailhook** [comment]
Just run it again, and it will choose another mirror. Or you can set the preferred mirror:
http://vagga.readthedocs.io/en/latest/settings.html#opt-alpine-mirror

**Comment by webknjaz** [comment]
It kept picking same mirror continuously. Thanks for the reference, I couldn't find it myself :)

**Comment by tailhook** [comment]
Do you mean, each time you get the same mirror? Or you just annoyed that it's being picked too often?

**Comment by webknjaz** [comment]
Yes. Each time. I guess, this happens because of some caching layer in Alpine's infrastructure.

**Comment by tailhook** [comment]
Then it's probably a bug. Should look at it.

**Comment by webknjaz** [comment]
The mirror has changed after some time. I don't think this is vagga's bug.
Still maybe it makes sense to temporary blacklist such mirrors automatically after failing to reach them a couple of times.

**Comment by tailhook** [comment]
The problem is that we don't fetch package list ourselves. Only apk/apt-get does that. So we can't be sure that mirror fails, it may be out of disk, no wi-fi, whatever....

**Comment by tailhook** [comment]
Well, I can't reproduce it. It picks a new mirror each time.
