### ISSUE TITLE
Add a warning if `vagga.yml` is present in the directory hierarcy

### ISSUE THREAD

**Issue by zemlanin** [tailhook/vagga#264]
🙍

**Comment by tailhook** [comment]
Well, I don't think it should. Mostly because if we support both `yml` and `yaml` there is an ambiguity of which is chosen when both are present.

I think the times when more than three character extension was a problem have already passed.

**Comment by tailhook** [comment]
By the way, if it is just common case for mistakes you're doing, we can add a warning if there is `vagga.yml` but not `vagga.yaml`. Is it something you appreciate?

**Comment by zemlanin** [comment]
It totally is. I guess, warning when there are both files can be helpful too

**Comment by tailhook** [comment]
Okay, I'm reopening the issue and marking it "easy". If no-one provides a pull request I'll fix it later.
