### ISSUE TITLE
Ubuntu failure load vagga 0.5.0

### ISSUE THREAD

**Issue by stepanov-valentin** [tailhook/vagga#270]
`Connecting to cdimage.ubuntu.com (91.189.92.164:80)
wget: server returned error: HTTP/1.1 404 Not Found
ERROR:vagga::builder::download: Error unlinking cache file: No such file or directory (os error 2)
ERROR:vagga::builder: Error building container "database": step Ubuntu("trusty") failed: Wget exited with status: exited with code 1
ERROR:vagga::wrapper: Error executing _build: Builder exited with code 1
`

`vagga  --version
v0.5.0
`
How can i manage this? @tailhook can you suggest some actions?

**Comment by tailhook** [comment]
Yes, it's known problem. You should install vagga from testing repo. We will make a release in few days if things go well.

(If you wonder it's not a problem of vagga itself, but ubuntu removing older images #230)

**Comment by stepanov-valentin** [comment]
@tailhook thx for your work, you are awesome)
