### ISSUE TITLE
Panic in supervise command when zero processes match condition

### ISSUE THREAD

**Issue by stepanov-valentin** [tailhook/vagga#289]
Try to run only children process of test !Supervise but get error:
` terminal: vagga test --only database`
`terminal: thread '<main>' panicked at 'assertion failed: children.len() > 0', src/launcher/supervisor.rs:299
note: Run with RUST_BACKTRACE=1  for a backtrace.
`
Same result when run:
`vagga test --only database`

@tailhook  any suggestions?

**Comment by tailhook** [comment]
I think there is no process `database` in your config. But we definitely need to have a better error message :)

**Comment by stepanov-valentin** [comment]
@tailhook your right, my mistake, need to be more attentive)

**Comment by tailhook** [comment]
We need to keep this open until we do fix the error message.
