### ISSUE TITLE
Handling system settings, like max_user_watches

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#291]
# Brief

Both ubuntu xenial and docker for mac has the following setting by default:
```
fs.inotify.max_user_watches = 8192
```
Which is too little for some projects (like the one of my employer)

Various tools react to exceeding limit (error `ENOSPC`) differently:

1. `webpack --watch` silently crashes
2. `nodemon` shows errno but doesn't say how to fix it
3. `werkzeug` ignores offending folder recursively (effectively ignoring the whole project dir in our case)
4. Some tools just fallback to slower `stat` calls (and they are super-slow on this number of files)

In perfect world, the tool will print a hint which is easy to follow. But sorry...

# Solution

Add a setting to a command:
```
  run: !Command
    expect-inotify-limit: 16384
```

Then we can:
1. By default: check and print warning if `max-user-watches` less than expected
2. When some user-level setting is enabled run `sudo sysctl fs.inotify.max_user_watches=16384`
3. In `vagga-docker` tweak `sysctl` by default

# In General

The bigger questions are:

1. Should we add system checks to vagga config?
2. Should we help user to tune the system to suit project? Or maybe it must be done in the shell script in the project itself?

My feel is that vagga is a tool for setting up development environments. So we should make them as easy as possible. And more important point is that, if you have discovered that `max_user_watches` is required for your program to function correctly, you should communicate it as simple as possible to other users.

The downsides are obviously: more code and config to learn. And sometimes maybe non-obvious attack vectors (i.e. making `max_user_watches` enormous)

/cc @warik, @popravich, @anti-social, @alxpy

**Comment by anti-social** [comment]
We can set reasonable limit for `expect-inotify-limit` setting.

**Comment by popravich** [comment]
> Should we add system checks to vagga config?

This sounds reasonable. 

> Should we help user to tune the system to suit project? 

I think this should be done in context of point 1, ie `vagga` can check system settings and report
what is wrong providing either http link to FAQ page explaining problem and fix or showing
steps need to be run to fix/change setting.
