### ISSUE TITLE
Untrusted repository

### ISSUE THREAD

**Issue by andreaferretti** [tailhook/vagga#299]
Right now, Vagga for Ubuntu is served on an untrusted repository. This breaks automatic updates. Would it be possible to add a key to the repository and sign the artifacts with it?

**Comment by tailhook** [comment]
Yes. I have to find the time to build that infrastructure. 

In the meantime you can use the following in the apt-sources.list:
```
deb [arch=amd64 trusted=yes] http://ubuntu.zerogw.com vagga main
```

Closing as dup of #149

**Comment by andreaferretti** [comment]
Thank you, I did not know about those settings
