### ISSUE TITLE
Unable to copy files onto the file system with setup in vagga.yaml

### ISSUE THREAD

**Issue by natemara** [tailhook/vagga#30]
I'm trying to use some custom apache config files with my vagga container. This is my `vagga.yaml`:

    containers:
      base_server:
        setup:
          - !Ubuntu trusty
          - !UbuntuUniverse
          - !Install [python3, python3-setuptools, python3-pip, phantomjs, apache2, php5, mysql-server]

      server_conf:
        setup:
          - !Sh cp -fr /work/apache-conf/ /etc/apache2/

      test:
        setup:
          - !Container server_conf
          - !Depends setup.py
          - !Sh "python3 setup.py install"

    commands:
      test: !Command
        container: server_conf
        run: bash

And this is the error that I get when I try to run it:

     λ vagga test
    ERROR:main: Error build command {"variant":"Sh","fields":["cp -fr /work/apache-conf/ /etc/apache2/"]}: Command ["/bin/sh", "-c", "cp -fr /work/apache-conf/ /etc/apache2/"] exited with status 127
    ERROR:main: Error executing _build: Builder exited with code 1
    Build returned 124

I've also tried using `!Cmd` with an explicit path, but then I get this error:

         λ vagga test
        ERROR:main: Error build command {"variant":"Cmd","fields":[["/bin/cp","-fr","/work/apache-conf/","/etc/apache2/"]]}: Command ["/bin/cp", "-fr", "/work/apache-conf/", "/etc/apache2/"] exited with status 127
        ERROR:main: Error executing _build: Builder exited with code 1
        Build returned 124

What's going on here?

**Comment by tailhook** [comment]
Probably you have missing ``!Container base_server`` in ``server_conf`` section. The ``Sh`` has nothing to run in an empty container.
