### ISSUE TITLE
Permission denied mounting proc

### ISSUE THREAD

**Issue by stepanov-valentin** [tailhook/vagga#310]
I build custom kernel for my pc and try to run vagga. But see this error:
`INFO:vagga::process_util: Running <Command "/usr/bin/id" "-u" "-n">
INFO:vagga::process_util: Running <Command "/proc/self/exe" ("vagga_wrapper") "_build" "database"; environ: {"RUST_LOG"="debug","TERM"="xterm","_VAGGA_HOME"="/home/stepanov",}; uid_map=[UidMap { inside_uid: 0, outside_uid: 1000, count: 1 }, UidMap { inside_uid: 1, outside_uid: 1214112, count: 65535 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1000, count: 1 }, GidMap { inside_gid: 1, outside_gid: 1214112, count: 65535 }]>
DEBUG:vagga::container::mount: Procfs mount "/home/stepanov/Projects/Python/lpschedule/.vagga/.mnt/proc"
DEBUG:vagga::container::mount: Pseusofs mount "/home/stepanov/Projects/Python/lpschedule/.vagga/.mnt/dev/pts" devpts newinstance
ERROR:vagga::wrapper: Error executing _build: Can't mount pseudofs "/home/stepanov/Projects/Python/lpschedule/.vagga/.mnt/dev/pts" (newinstance, options: devpts): Operation not permitted (os error 1)
Command <Command "/proc/self/exe" ("vagga_wrapper") "_build" "database"; environ: {"RUST_LOG"="debug","TERM"="xterm","_VAGGA_HOME"="/home/stepanov",}; uid_map=[UidMap { inside_uid: 0, outside_uid: 1000, count: 1 }, UidMap { inside_uid: 1, outside_uid: 1214112, count: 65535 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1000, count: 1 }, GidMap { inside_gid: 1, outside_gid: 1214112, count: 65535 }]> exited with code 124
`

uname -r
`4.6.4-zen`
I need to config my kernel for using vagga, or this is fresh kernel problem?

**Comment by tailhook** [comment]
It looks like you need to set the following kernel option:
```
CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
```

**Comment by stepanov-valentin** [comment]
That's help, thank you for help.
