### ISSUE TITLE
Python multiprocessing error

### ISSUE THREAD

**Issue by bitc** [tailhook/vagga#32]
There is an error when trying to run Python programs that use the "multiprocessing" module.

This is what is supposed to happen on a regular system:

```
$ python2.7 
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing
>>> multiprocessing.Pool(2)
<multiprocessing.pool.Pool object at 0x7febc82b93d0>
>>> 
```

But this is what happens when run inside vagga (Ubuntu trusty container):

```
# python2.7 
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing
>>> multiprocessing.Pool(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 138, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 234, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
>>> 
```

From a brief investigation is looks like this is because of a problem accessing `/dev/shm`. References:

* [Permission Denied - LXC Python 2.7 Multiprocessing](https://github.com/omniscale/imposm/issues/9)
* [Python multiprocessing: Permission denied](http://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied)
* [Setting up schroot for Python multiprocessing](http://falstaff.agner.ch/2013/10/29/setting-up-schroot-for-python-multiprocessing/)

(I'm experiencing this issue when trying to use emscripten, which uses Python multiprocessing)

**Comment by tailhook** [comment]
Hm, it works for me. Does your host system have /dev/shm? Is it a symlink? What are permissions?

Since vagga uses `/dev` from host system, that one should have `/dev/shm` folder. If it conflicts you might try:
```
  volumes:
    /dev/shm: !Tmpfs
        size: 100Mi
        mode: 0o1777
```
(but the directory `/dev/shm` must exist on host system anyway)

**Comment by bitc** [comment]
My host system is Ubuntu 14.04. On my host system `/dev/shm` is a symlink to `/run/shm`

Could the problem be that inside vagga `/run` is readonly?

**Comment by tailhook** [comment]
Yes, it's probably is. You can create `/run/shm` during build and then mount `tmpfs` over `/run/shm`. Or you may try to mount the whole `/run` as `tmpfs` inside container, but I'm not sure if glibc (or whatever provides semaphore implementation), is smart enough to create the folder.

Anyway, let me know what works for you, we should probably provide some universal solution in vagga itself

**Comment by bitc** [comment]
The directory `/run/shm` already exists inside the container. So I just added:

``` yaml
    volumes:
      /run/shm: !Tmpfs { size: 100Mi, mode: 0o1777 }
```

and now it seems to be working.

I agree that vagga should have a universal solution builtin, and that shared memory should "just work". As I understand, `vagga.yaml` files are supposed to be portable across all Linux distros, without requiring specific hacks for specific host distros.
