### ISSUE TITLE
Unpack tar itself instead of using busybox

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#33]
Try using https://crates.io/crates/tar-parser

**Comment by tailhook** [comment]
Probably we should use https://crates.io/crates/tar instead, as it is used by cargo.

**Comment by tailhook** [comment]
Preliminary support is available in df84d71 (``newtar`` branch)

**Comment by anti-social** [comment]
Didn't see your comment so started to work on this too =) 

https://github.com/anti-social/vagga/commit/cd13b9ab280b7ee8da5ad7bdbd16eb82ce0336ed

I decided not to implement low level unpacking. Think tar library should do all that work.

**Comment by tailhook** [comment]
It's been already merged into the master.
