### ISSUE TITLE
`remount_ro` should obey `nosuid,nodev`

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#358]
In current setup when we are trying to remount to readonly the filesystem set up with `nosuid,nodev` we are getting a `Permission denied` error.

Same issue is probably with running vagga on tmpfs that we observed earlier.

**Comment by roman901** [comment]
I dont think that it can be fixed. Vagga suggests that suid will be modifyed, as I understanded

**Comment by tailhook** [comment]
I'm not sure. But presumably, we must read flags from the initial mountpoint and pass them when doing `mount(...MS_REMOUNT,MS_RDONLY..)`. (Otherwise, kernel thinks we are trying to reset them, i.e. get rid of nosuid, nodev)
