### ISSUE TITLE
Invalid calculations of uidmap

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#366]
Here is relevant panic.
```$ vagga _clean --unused
thread '<main>' panicked at 'arithmetic operation overflowed', src/config/range.rs:52
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This is a bug in range calculations. Fixing it in most straightforward and sensible way means changing hashes of all containers.

We can either patch only this and keep technical debt by hardcoding `-1` in hash function. Or fix it in most sensible way and require everyone to rebuild (all hashes will change). If we choose latter we might take a step further to clean up technical debt from all command hash functions.

/cc @anti-social

**Comment by anti-social** [comment]
Can't understand about hardcoding `-1` in hash function. How can we fix it patching hash function whereas it fails inside `Range::end` method?

I think we can even fix it without changing all containers hashes. It seems I managed to fix this error without changing hashes.

Also can you give me a point how to reproduce this bug? I can only reproduce it by adding into `/etc/subuid` file `100000:4294867295` range and into container settings next option: `uids: ["100000-4294967294"]`. And when I change container `uids` option to `["100000-4294967295"]` vagga fails elsewhere:
```
thread '<main>' panicked at 'arithmetic operation overflowed', src/config/range.rs:39
```

**Comment by tailhook** [comment]
It's reproduced by running `vagga _clean --unused` in vagga-docker. Probably you may create some container as root and run clean.

> Can't understand about hardcoding -1 in hash function. How can we fix it patching hash function whereas it fails inside Range::end method?

IIRC the problem is that we [increment](https://github.com/tailhook/vagga/blob/master/src/config/range.rs#L39) end variable [twice](https://github.com/tailhook/vagga/blob/master/src/config/range.rs#L52). So we basically get wrong range in all calculations. It's not visible because larger that needed range just works :)

In docker it fails on "max uidmap" because maximum user id that we use in the range is maximum uid allowed. And it fails only on clean just because we use "max uidmap" only for clean.

But if we fix range to not to make range larger that it should be we will brake code that does hashing.
