### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by slinstaedt** [tailhook/vagga#38]
As not being an expert in rust, it's not clear to me, if vagga supports configuration and usage of http proxies instead of trying to establish direct connections?

**Comment by tailhook** [comment]
If you're talking about using proxy when building image. Then it does not support at the moment. It should be easy to implement (mostly forward http_proxy env variable). But I'm busy with porting vagga to rust 1.0. Until that I will not fix the issue.

As a temporary workaround you might use `!Env` command to set proxy yourself (but it may not work for some built-in commands like TarInstall).

Inside the container you may use proxy as always. But vagga does not propagate env vars by default (probably I will fix it, but I'm not sure if it is a security issue to propagate by default). Look at [docs](http://vagga.readthedocs.org/en/latest/environment.html) for environment settings.

**Comment by slinstaedt** [comment]
As far as I see, the container is not even downloaded at all:
```
vagrant@vagrant-ubuntu-trusty-64:~/test$ cat vagga.yaml
containers:
  flask:
    setup:
    - !Ubuntu trusty
    - !UbuntuUniverse
    - !Install [python3-flask]
commands:
  py3: !Command
    container: flask
    run: python3
vagrant@vagrant-ubuntu-trusty-64:~/test$ vagga py3
Connecting to cdimage.ubuntu.com (91.189.92.174:80)
wget: can't connect to remote host (91.189.92.174): Operation timed out
ERROR:main::download: Error unlinking cache file: couldn't unlink path (no such file or directory (No such file or directory); path=/vagga/cache/downloads/0e78368d-trusty-core-amd64.tar.gz.part)
ERROR:main: Error build command {"variant":"Ubuntu","fields":["trusty"]}: Wget exited with status: exit code: 1
ERROR:main: Error executing _build: Builder exited with code 1
```


The process hangs some minutes. Because I do not see any request from vagga in the proxy log, I guess it is trying to connect directly. Env variables `http_proxy` and `https_proxy` are set correctly and are working for apt and lynx e.g.

**Comment by tailhook** [comment]
Try the following workaround:
```
containers:
  flask:
    setup:
    - !Env { http_proxy: "your proxy url" }
    - !Ubuntu trusty
    - !UbuntuUniverse
    - !Install [python3-flask]
commands:
  py3: !Command
    container: flask
    run: python3
```

**Comment by tailhook** [comment]
Should be fixed now. The build will soon be in the testing repository.
