### ISSUE TITLE
On Alpine v3.5, install php7 from community or php5 from main?

### ISSUE THREAD

**Issue by livioribeiro** [tailhook/vagga#385]
Alpine v3.5 was launched with php7 available but only in community repository. I assumed it would come into main repository.

Should vagga install php7 from the community repository or keep php5 from main?

**Comment by tailhook** [comment]
I'm not sure. Is there any difference between php installed in v3.4 and v3.5?

(is it blocker for releasing v0.7.0?)

**Comment by livioribeiro** [comment]
The only difference is the availability of php7 in the community repository, php5 is the same.

I just forgot to mention this is a bug, right now php installation in alpine v3.5 fails because my implementation assumed php7 would be in the main repository, but it is not (you have to enable community repository).

It is probably better stay with the main repository, and the bug is really quick to fix.

**Comment by tailhook** [comment]
Okay. Let's fix it so that php5 is used by default, like in v3.4, so that upgrade path (from v3.4 -> v3.5) would be simpler.

It should be easy enough to install php7 from the community using `!Repo` command. Example of doing that is really appreciated, though.

**Comment by tailhook** [comment]
Would you like to make a pull request?

**Comment by livioribeiro** [comment]
I'm working on it, just having some trouble automatically creating a symlink to put "php" on PATH when using a custom runtime (php7 package does not auto symlink to /usr/bin/php)
