### ISSUE TITLE
More powerful Copy and Depends

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#389]
We want something like this:
```
!Copy
source: /work
rules:
- "*.py"
- "public/js/**/*.js"
- "/config"
- "!*~"
- "!*.old"
path: /some/dest
```

I.e. a list of rules similar to `.gitignore` rules, but reverse

/cc @anti-social

**Comment by Orhideous** [comment]
Will this feature imprement recursive `!Depends` on entire folder?

**Comment by anti-social** [comment]
We decided to support only absolute paths for including rules. It'll allow us to ignore non-matching directories.
