### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by ahri** [tailhook/vagga#4]
I'm unfamiliar with rust so I've not tried to work this out myself. I installed the rust nightly (https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz) on Fedora 22 specifically to try out Vagga :) Here's the error:

    $ make
    warning: --print-file-name has been deprecated in favor of --print file-names
    warning: --print-file-name has been deprecated in favor of --print file-names
    make -C rust-quire quire-lib
    make[1]: Entering directory '/home/adam/repos/vagga/rust-quire'
    warning: --print-file-name has been deprecated in favor of --print file-names
    rustc -g -o libquire.rlib src/lib.rs
    src/parser.rs:138:54: 138:56 error: this form of character escape may only be used with characters in the range [\x00-\x7f]
    src/parser.rs:138                             Some('N') => res.push('\x85'),
                                                                           ^~
    src/parser.rs:139:54: 139:56 error: this form of character escape may only be used with characters in the range [\x00-\x7f]
    src/parser.rs:139                             Some('_') => res.push('\xa0'),
                                                                           ^~
    src/parser.rs:140:53: 140:58 warning: \U00ABCD12 and \uABCD escapes are deprecated
    src/parser.rs:140                             Some('L') => res.push('\u2028'),
                                                                          ^~~~~
    src/parser.rs:140:53: 140:58 help: use \u{ABCD12} escapes instead
    src/parser.rs:140                             Some('L') => res.push('\u2028'),
                                                                          ^~~~~
    src/parser.rs:141:53: 141:58 warning: \U00ABCD12 and \uABCD escapes are deprecated
    src/parser.rs:141                             Some('P') => res.push('\u2029'),
                                                                          ^~~~~
    src/parser.rs:141:53: 141:58 help: use \u{ABCD12} escapes instead
    src/parser.rs:141                             Some('P') => res.push('\u2029'),
                                                                          ^~~~~
    src/parser.rs:637:58: 637:59 error: obsolete syntax: `|uint| -> bool` closure type syntax
    src/parser.rs:637 pub fn parse<'x, T>(name: Rc<String>, data: &str, process: |Document| -> T)
                                                                               ^
    note: use unboxed closures instead, no type annotation needed
    src/emit.rs:198:17: 198:18 error: expected one of `.`, `;`, or `}`, found `S`
    src/emit.rs:198                 S::Fin }
                                    ^
    Makefile:9: recipe for target 'libquire.rlib' failed
    make[1]: *** [libquire.rlib] Error 101
    make[1]: Leaving directory '/home/adam/repos/vagga/rust-quire'
    Makefile:31: recipe for target 'quire' failed
    make: *** [quire] Error 2

**Comment by tailhook** [comment]
You should use rust 0.12 for vagga. I don't keep up to date with rust nightly because it may change any day.

**Comment by ahri** [comment]
Ah, figures :) Thanks a lot, that got it compiled.
