### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [tailhook/vagga#416]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would need from Serde or another library before this would be possible?

**Comment by tailhook** [comment]
Yes we rely on `rust-quire` which uses rustc-serialize

**Comment by tailhook** [comment]
Seems to be done in the master now, thank you for reporting!
