### ISSUE TITLE
Py2Compile & Py3Compile commands

### ISSUE THREAD

**Issue by anti-social** [tailhook/vagga#444]
Think it is worth to implement those commands.

At the moment we write next:
```yaml
- !BuildDeps [faketime]
- !Env
  PYTHONHASHSEED: 0
- !Sh faketime -f '1970-01-01 00:00:01' python3.6 -m compileall ./app
```

Motivation:
- Simplification of reproducible builds of deploy containers

```yaml
- !Py3Compile /app
```

Unfortunately there isn't `faketime` package in the Alpine repositories. Thus those commands won't be accessible for Alpine containers.

**Comment by tailhook** [comment]
Note: it should probably obey `python_exe` in `PipConfig`

**Comment by anti-social** [comment]
The problem was in the `!Copy` command, it set modification time of the files to the current time. So we will fix it in https://github.com/tailhook/vagga/pull/445

Also we can try to make `Py2Install` & `Py3Install` commands reproducible.
