### ISSUE TITLE
Alternative yarn approach

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#453]
Currently we have two issues with yarn:
1. `--modules-folder` doesn't work (yarnpkg/yarn#3792)
2. `npm run prepublish` is run when installing, we don't need that

While issue (1) might be fixed in future, issue (2) may be related to (1) but may be fixed when (1) is fixed or maybe not.

So alternative approach would be to extract `*dependencies` portion of packages json into `/usr/lib/node_modules/package.json` and copy `yarn.lock`, the do yarn install there. Then copy yarn.lock  back.

Any obvious downsides of that? I think it may be problematic if anything other than our supported subset of `package.json` is used for installation. (or should be blacklist items there rather than whitelist?)

/cc @playpauseandstop, @anti-social, @alexmost

**Comment by playpauseandstop** [comment]
Am OK with solution, only comment to have `/usr/lib/node_modules` configurable in `vagga.yaml` as `!YarnDependencies` option or environment var.

**Comment by tailhook** [comment]
Okay, currently we use `bind-mount for `./node_modules`, it's mostly fine.
