### ISSUE TITLE
vagga --version requires vagga to satisfy minimum-vagga from config

### ISSUE THREAD

**Issue by playpauseandstop** [tailhook/vagga#459]
This is a continue of #457 

Even if you have vagga config, but `minimum-vagga` not matched it will outputs with,

```
$ vagga --version
/home/playpauseandstop/Projects/evo/evodoc/vagga.yaml:4:16: Minimum Vagga Error: Please upgrade vagga to at least "0.8.1"
```

instead of printing `vagga` version to stdout, which is strange.

**Comment by tailhook** [comment]
Done since `v0.8.0-4-gb5edfc0`
