### ISSUE TITLE
_build_shell : Error symlinking

### ISSUE THREAD

**Issue by rainboh** [tailhook/vagga#479]
$ vagga _build_shell 
ERROR:vagga::wrapper::debug: Error symlinking "[": Permission denied (os error 13)

Nevertheless build shell is entered but cmd set is limited, e.g. "ls" is not available

Issue is not detected by 

$ bats readonly.bats 
 ✓ Vagga list works
 ✓ Empty vagga has code 127
 ✓ Vagga build shell

3 tests, 0 failures

**Comment by tailhook** [comment]
Can reproduce it locally. Will look at it soon.
