### ISSUE TITLE
Fails on build from source

### ISSUE THREAD

**Issue by flyingP0tat0** [tailhook/vagga#490]
*Architecture:* x86_64
*OS:* Solus
*Rust triple:* x86_64-unknown-linux-gnu

I built vagga from source:
```shell
VAGGA_VERSION=0.8.0 cargo build --release
```

When trying to run anything, vagga exits with the following (from redis example):
```shell
ERROR:vagga::wrapper: Error executing _build: Could not run versioner: error when executing: No such file or directory (os error 2)
Command <Command "/proc/self/exe" "__wrapper__" "_build" "ubuntu"; environ[3]; uid_map=[UidMap { inside_uid: 0, outside_uid: 1000, count: 1 }, UidMap { inside_uid: 1, outside_uid: 689824, count: 65535 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1000, count: 1 }, GidMap { inside_gid: 1, outside_gid: 689824, count: 65535 }]> exited with code 124
```

`/etc/sub[ug]id` should also be setup correctly:
```shell
$ grep $(id -un) /etc/sub[ug]id
/etc/subgid:me:689824:65536
/etc/subuid:me:689824:65536
```

I just don't really know where to begin with resolving this...

**Comment by flyingP0tat0** [comment]
Alright, I just realized just building from source won't do the trick. I used the provided binary from the documentation, installed it using the provided script and now it works.

**Comment by tailhook** [comment]
Yes, the supported way to build vagga is `make` . Apart from building vagga itself it also downloads busybox and apk. Of course, even better way is `vagga make` :)

**Comment by flyingP0tat0** [comment]
Yeah, but that gets difficult when your distro doesn't provide vagga :D
