### ISSUE TITLE
ubuntu.zerogw.com - certificate verification failed

### ISSUE THREAD

**Issue by tomikais** [tailhook/vagga#543]
`E: Failed to fetch https://ubuntu.zerogw.com/dists/vagga/main/binary-amd64/Packages  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification.`

**Comment by tailhook** [comment]
Fixed. Sorry for long delay. Was on vacation.
