### ISSUE TITLE
Job opportunity

### ISSUE THREAD

**Issue by KristiSunny** [tailhook/vagga#547]
Привітик, чи цікавлять вас нові проекти? Шукаємо Senior Python для наших партнерів з офісом у Києві (рорбота на ремоуті з можливими відрядженнями у Київ)  з крутим проектом і хорошою оплатою. Розширяють команду, аналізують крипту та дають аналітику по валюті. Також співпраця з біржами, банками, фондами. Якщо цікавить звертайтесь 😊 мій Skype - Khrystyna Zh , mail: seven.khrystyna.zh@protonmail.com т. 0638669440

**Comment by tailhook** [comment]
Це погана ідея писати про вакансії тут.
