### ISSUE TITLE
can't mount tmpfs on ubuntu 14.04

### ISSUE THREAD

**Issue by popravich** [tailhook/vagga#62]
```
ERROR:vagga::wrapper: Error executing test: Can't mount /dev/shm: Can't mount tmpfs "/vagga/root/run/shm" (options: size=100m,mode=01777): No such file or directory (os error 2)
```

**Comment by piranna** [comment]
I'm having this same problem with latest code (pre-0.4.1), only that with `/vagga/root/run`. I'm not sure if that folder should be created on the root filesystem in any case...

**Comment by tailhook** [comment]
@piranna just pushed fix to master. Binary package will be up in few hours (because buildbot is doing time-cosuming rebuild of container)

**Comment by piranna** [comment]
Ah cool :-)

**Comment by tailhook** [comment]
@piranna Unfrotunately buildbot is still broken, I'll try to fix it later today. FYI, you will need at least v0.4.0-24-g8c48351

**Comment by piranna** [comment]
I'm using vagga-testing repo, so I'll get the correct version when it gets published :-)
