### ISSUE TITLE
Thread panick when trying to pass all my environment variables

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#63]
I have a Lot of variables that I need to pass to the build environment(because I cross-compile, I overwrite and declare a lot of variables). I didn't expect it to work but I tried to execute this command `vagga -e $(env) display-env`, where `display-env` just calls `env`.

Result:
`thread '<main>' panicked at 'failed setenv: Invalid argument (os error 22)', src/libstd/sys/unix/os.rs:435`

**Comment by tailhook** [comment]
Which version of vagga do you use (stable or testing)?
Could you run ``RUST=log RUST_BACKTRACE=1 vagga -e ...`` ?
Is it possible that environment contains non-ascii and/or invalid utf8?

**Comment by tailhook** [comment]
Ah, okay, I can reproduce this. Actually there are three issues:
1. `vagga -e` requires only env variable name, like `vagga -e PATH`, not pair. And environment variable name can't contain equals `=` character. You may use `vagga -E PATH=xxx`
2. You can't pass multiple arguments this way. You need some complex stuff like `vagga  $(a=($(env)); printf "-E %q\n" $a) display-env` (in bash). (i.e. prefix each arg with `-E` and quote special characters).
3. Error is misleading. Will fix it

The size of environment doesn't matter (as long as it shorter than 4 Mib AFAIR). Do you really need to propagate all the environment, or may be you're better served by putting data into file inside container, and use `environ-file` in configuration?

**Comment by tailhook** [comment]
Fixed the error reporting issue in master. Feel free to open another issue if you need some convenience for passing lots of environment variables.

**Comment by lilianmoraru** [comment]
Good idea with `environ-file`(I got confused about the line-wrapping mention and didn't use it). Could be a topic in `Tips and Tricks` when you need many variables to be declared, although it might not be appropriate since it seems that you would mention it again.

**Comment by tailhook** [comment]
@lilianmoraru, feel free to submit pull request for updating docs. It's hard to find a good wording for every piece of docs, especially for me as I'm proficient with my own tool :). A bit of duplication in the docs is perfectly okay.
