### ISSUE TITLE
Sometimes dpkg fails to install package, probably because of selinux

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#65]
Here is the relevant error message (more is in #6)
```
dpkg: error processing archive /var/cache/apt/archives/libjs-jquery_1.7.2+dfsg-2ubuntu1_all.deb (--unpack):
 cannot get security labeling handle: No such file or directory
```
Presumably it's because host system uses selinux (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734193). As far as I understand the host system is fedora 22.

**Comment by sashasimkin** [comment]
Yes, you're right, disabling SELinux does the trick. And yes, host system is Fedora 22.
For ones with Fedora(but other distro's as well perhaps) who'll encounter this here's [the solution](https://docs.fedoraproject.org/en-US/Fedora/11/html/Security-Enhanced_Linux/sect-Security-Enhanced_Linux-Enabling_and_Disabling_SELinux-Disabling_SELinux.html).

> And please, don't put many additional things to unrelated issue, it makes things hard to find

Sure, I just didn't know that it's unrelated. Sorry.

Thanks!

**Comment by tailhook** [comment]
We should probably do thing similar to systemd: https://github.com/systemd/systemd/commit/d8fc6a000fe21b0c1ba27fbfed8b42d00b349a4b
Instead of relying on solution described in the debian bugtracker.

**Comment by tailhook** [comment]
Works for me in vagrant, since 4c09b15. @sashasimkin, can you confirm?

**Comment by sashasimkin** [comment]
Thanks, I'll try tomorow. Just to clarify: I need to install from `testing`?

**Comment by tailhook** [comment]
Yes, and it must be at least `0.3.0-74-g4c09b15` (just restarted buildbot, it failed to build yesterday). Package should be in the repo in 20 minutes or so.

**Comment by sashasimkin** [comment]
@tailhook Looks like it not:
> $ curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh
...
2015-10-09 18:13:57 (1,07 MB/s) - ‘vagga-0.3.0-**72**-gc10f011.tar.xz’ saved [4299332/4299332]

Am I miss something?

**Comment by tailhook** [comment]
@sashasimkin, fixed the buildbot. New version is already in testing repo.

**Comment by tailhook** [comment]
Okay, I consider this fixed. Feel free to reopen if it's not.
