### ISSUE TITLE
Let scripts export environment variables

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#67]
First of all, would it be ok if scripts (!Sh) could export environment variables?
Vagga's build `vagga make-release` could be faster for example. I tried to get the number of system reported cores and pass to make `-j $MAKE_JOBS`. For example, my system reports 8 cores(hyperthreading), it could definitely compile faster if it would of used all cores.

Here is the script I am trying to run:
```bash
if [ -z "$MAKE_JOBS" ]; then
  MAKE_JOBS=$(( $(grep "^physical id" /proc/cpuinfo | wc -l) + 1 ))
  if [ "$MAKE_JOBS" -eq 0 ]; then
    MAKE_JOBS=$(( $(grep "physical" /proc/cpuinfo | wc -l) + 1 ))
  fi
fi

export MAKE_JOBS=$MAKE_JOBS
```

While it could be possible to pass it in the shell while `run:` is executed, I wanted to reduce code duplication.
Is it possible to run some shell code to set an environment variable and then use it in `commands:`?

**Comment by lilianmoraru** [comment]
I guess the script is not 'sourced' and for good reasons(exit, ...).
Should this kind of operations instead be put in a file and source them in `run:`?
It seems like a workaround to me, I don't know.

**Comment by tailhook** [comment]
Yes, we can't source `!Sh` on each run because because they usually do some work (i.e. install packages).

And yes, you can just source arbitrary things in `run`:
```
commands:
  make: !Command
    accepts-arguments: true
    run: |
      . ./helpers.sh
      make "$@"
```
