### ISSUE TITLE
Can't specify relative path in vagga settings

### ISSUE THREAD

**Issue by sashasimkin** [tailhook/vagga#69]
Created file `$HOME/.vagga.yaml`. Put there `~/.vagga/.cache` and `$HOME/.vagga/.cache`, but either case says me:
> Cache directory ($HOME|~)/.vagga/.cache must exists. Please either create it or remove that configuration setting

So I had to put absolute paths. Is it intended?

**Comment by tailhook** [comment]
Well, it's not relative path. It's the path that requires some variable expansion.

I'm not sure yet. Probably arbitrary environment variable expansions will not work. As well as `~user` for arbitrary users. But maybe just `~/` can be implemented.
