### ISSUE TITLE
just cannot _run

### ISSUE THREAD

**Issue by grubberr** [tailhook/vagga#7]
Hello,

root@alpaca-dev:~# cat vagga.yaml 
containers:
  ubuntu:
    setup:
    - !Ubuntu trusty
    - !Install [python]

root@alpaca-dev:~# vagga _run ubuntu uptime
thread '<main>' panicked at 'internal error: entered unreachable code', src/container/uidmap.rs:99

**Comment by tailhook** [comment]
Hi,

Your probably don't have your user in `/etc/subuid` and/or `/etc/subgid`. I should fix the panic though :)

**Comment by grubberr** [comment]
running under non-root user - helped

**Comment by tailhook** [comment]
Hm, any reasons you tried as root?

I need to fix running as root too, but mostly for container-in-container scenarios. I believe running as root is not a good idea per se :)

**Comment by grubberr** [comment]
no reason, just run as is on newly created virtual machine

**Comment by tailhook** [comment]
Fix both issues in https://github.com/tailhook/vagga/commit/34a55138b0ea6533a086cd463a30e1e022421d11 and https://github.com/tailhook/vagga/commit/f8741755f7f9b9c78c2299e90e4b560848cfb568
