### ISSUE TITLE
Probably wrong dependency management

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#70]
Please check this gist(vagga.yaml is at the bottom, github decided to sort them):
https://gist.github.com/lilianmoraru/b904d6d68f8cc59fd2db

Observe that in `linux-versions.yaml` it uses container `install_dep` and in `configs.yaml`, containers `qmake_[release/debug]` also use `install_dep`. `qmake_[release/debug]` set an environment variable differently. This makes `build-[release/debug]` create 2 different containers and installs all the software all over again(I should also mention that for some reason these environment variables don't propagate down to the commands).
This issue could be harder to manage(probably needed a State Machine for that to manage all the cases). At the same time, is this to be expected? Should changing an environment variable be considered harmful, in the sense that it could change the way the package-manager installs the software?

**Comment by tailhook** [comment]
I've only skimmed the config. But it seems you get `environ` wrong. It changes environment at **runtime** rather than container build time. You need ``!Env`` for changing build environment.

However, I'm not sure whether `environ` is merged from `!SubConfig` (probably not, just like volumes and other things, except setup). I think in many cases I want `environ` to clearly show what environment is. If you want to build it from multiple things, you may probably append lines to `/etc/environment` and use `environ-file`.

**Comment by lilianmoraru** [comment]
I changed to `!Env` but it doesn't save me from 2 copies of the crates.
Also, moving `!Env` under `!SubConfig` made the container rebuild all over again. My guess is that vagga remembers the modification timestamp of the file or the hash which I think is appropriate for tools like `Make` because they work with many files but here the tool could work based on properties changes for the files with different timestamps.

Just letting you know... I can find work-arounds...

**Comment by tailhook** [comment]
Is this one still actual?

**Comment by lilianmoraru** [comment]
@tailhook I have to go to work and cannot check right now but I don't think anything changed here.
The issue is that you have a container(`c1`) that does `- !Install [something]` and nothing else, it just runs `apt-get install -y`(on Ubuntu) and another container(`c2`) which just exports an environment variable.
If you use both with `!SubConfig`s in container `c3` and you change the environment variable in `c2`, it will rebuild. It does not do analysis like that(only `apt-get install -y` is run and there is no `!Sh` or anything like that? Ok, then changing an environment variable does not affect the only command running here which is `!Install`).
That of course if the environment variable cannot change the behavior of `apt-get`.

This of course needs deeper analysis and has to understand how the package manager of every Linux image used is working...
I'd say close it.

**Comment by tailhook** [comment]
Looks like nobody complained about this for years, so closing.
