### ISSUE TITLE
Simultaneous build breaks container

### ISSUE THREAD

**Issue by sashasimkin** [tailhook/vagga#80]
When I try to build same container twice in different shell sessions it breaks ike this (but in general error depends on moment when I start second build):
First session:
> $ vagga _build elastic
Get:1 http://archive.ubuntu.com trusty-proposed InRelease [212 kB]
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty InRelease
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates InRelease
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security InRelease       
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty Release.gpg              
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/main Sources     
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/restricted Sources
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/main amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/restricted amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/universe amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/main Translation-en
Get:2 http://archive.ubuntu.com trusty-proposed/main amd64 Packages [118 kB]   
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/restricted Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/universe Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty Release                  
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/main Sources    
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/restricted Sources
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/main amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/restricted amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/universe amd64 Packages
Get:3 http://archive.ubuntu.com trusty-proposed/restricted amd64 Packages [28 B]
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/main Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/restricted Translation-en
Hit http://archive.ubuntu.com trusty-proposed/main Translation-en              
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/universe Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main Sources             
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted Sources       
Hit http://archive.ubuntu.com trusty-proposed/restricted Translation-en        
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main amd64 Packages      
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/universe amd64 Packages  
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/universe Translation-en
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main Translation-en_US   
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted Translation-en_US
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/universe Translation-en_US
Fetched 330 kB in 2s (141 kB/s)
E: Unable to change to (unreachable)// - chdir (2: No such file or directory)
ERROR:vagga::builder: Error building container "elastic": Command <Command "/usr/bin/apt-get" "update"; environ: {"DEBIAN_FRONTEND"="noninteractive","HOME"="/tmp","TERM"="dumb","PATH"="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games","LANG"="en_US.UTF-8",}; chroot="/vagga/root"; work-dir="/work"> exited with code 100
ERROR:vagga::wrapper: Error executing _build: Builder exited with code 1
Command <Command "/proc/self/exe" ("vagga_wrapper") "_build" "elastic"; environ: {"TERM"="xterm","VAGGA_USER_HOME"="/home/sima","RUST_LOG"="warn",}; uid_map=[UidMap { inside_uid: 0, outside_uid: 1000, count: 1 }, UidMap { inside_uid: 689824, outside_uid: 689824, count: 65536 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1000, count: 1 }, GidMap { inside_gid: 689824, outside_gid: 689824, count: 65536 }]> exited with code 124

Second session:
> $ vagga _build elastic
Hit http://archive.ubuntu.com trusty-proposed InRelease
Hit http://archive.ubuntu.com trusty-proposed/main amd64 Packages
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty InRelease                
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates InRelease        
Hit http://archive.ubuntu.com trusty-proposed/restricted amd64 Packages        
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security InRelease       
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty Release.gpg              
Hit http://archive.ubuntu.com trusty-proposed/main Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/main Sources     
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/restricted Sources
Hit http://archive.ubuntu.com trusty-proposed/restricted Translation-en        
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/main amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/restricted amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/universe amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/main Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/restricted Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-updates/universe Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/main Sources    
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/restricted Sources
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/main amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/restricted amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/universe amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/main Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/restricted Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty-security/universe Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty Release                  
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main Sources
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted Sources
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main amd64 Packages      
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted amd64 Packages
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/universe amd64 Packages  
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main Translation-en      
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted Translation-en
Hit http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/universe Translation-en  
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/main Translation-en_US   
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/restricted Translation-en_US
Ign http://ubuntu-mirror.neocom.org.ua/ubuntu/ trusty/universe Translation-en_US
Reading package lists... Done 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  binutils cpp cpp-4.8 dpkg-dev g++ g++-4.8 gcc gcc-4.8 libasan0 libatomic1
  libc-dev-bin libc6-dev libcloog-isl4 libdpkg-perl libexpat1-dev
  libgcc-4.8-dev libgmp10 libgomp1 libidn11 libisl10 libitm1 libmpc3 libmpfr4
  libpython3-dev libpython3.4 libpython3.4-dev libquadmath0 libstdc++-4.8-dev
  libtimedate-perl libtsan0 linux-libc-dev make openssl patch python3.4-dev
  xz-utils
Suggested packages:
  binutils-doc cpp-doc gcc-4.8-locales debian-keyring g++-multilib
  g++-4.8-multilib gcc-4.8-doc libstdc++6-4.8-dbg gcc-multilib manpages-dev
  autoconf automake1.9 libtool flex bison gdb gcc-doc gcc-4.8-multilib
  libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan0-dbg
  libtsan0-dbg libquadmath0-dbg glibc-doc libstdc++-4.8-doc pkg-config
  make-doc ed diffutils-doc
Recommended packages:
  fakeroot libalgorithm-merge-perl libfile-fcntllock-perl xml-core
The following NEW packages will be installed:
  binutils build-essential ca-certificates cpp cpp-4.8 dpkg-dev g++ g++-4.8
  gcc gcc-4.8 libasan0 libatomic1 libc-dev-bin libc6-dev libcloog-isl4
  libdpkg-perl libexpat1-dev libgcc-4.8-dev libgmp10 libgomp1 libidn11
  libisl10 libitm1 libmpc3 libmpfr4 libpython3-dev libpython3.4
  libpython3.4-dev libquadmath0 libstdc++-4.8-dev libtimedate-perl libtsan0
  libxml2 libxml2-dev libxslt1-dev libxslt1.1 linux-libc-dev make openssl
  patch python3-dev python3.4-dev wget xz-utils
0 upgraded, 44 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/57.1 MB of archives.
After this operation, 156 MB of additional disk space will be used.
Extracting templates from packages: 100%
Preconfiguring packages ...
E: Can not write log (Is /dev/pts mounted?) - openpty (13: Permission denied)
Selecting previously unselected package libidn11:amd64.
(Reading database ... 11538 files and directories currently installed.)
Preparing to unpack .../libidn11_1.28-1ubuntu2_amd64.deb ...
Unpacking libidn11:amd64 (1.28-1ubuntu2) ...
Selecting previously unselected package libxml2:amd64.
Preparing to unpack .../libxml2_2.9.1+dfsg1-3ubuntu4.4_amd64.deb ...
Unpacking libxml2:amd64 (2.9.1+dfsg1-3ubuntu4.4) ...
Selecting previously unselected package libasan0:amd64.
Preparing to unpack .../libasan0_4.8.4-2ubuntu1~14.04_amd64.deb ...
Unpacking libasan0:amd64 (4.8.4-2ubuntu1~14.04) ...
Selecting previously unselected package libatomic1:amd64.
Preparing to unpack .../libatomic1_4.8.4-2ubuntu1~14.04_amd64.deb ...
Unpacking libatomic1:amd64 (4.8.4-2ubuntu1~14.04) ...
Selecting previously unselected package libgmp10:amd64.
Preparing to unpack .../libgmp10_2%3a5.1.3+dfsg-1ubuntu1_amd64.deb ...
Unpacking libgmp10:amd64 (2:5.1.3+dfsg-1ubuntu1) ...
Selecting previously unselected package libisl10:amd64.
Preparing to unpack .../libisl10_0.12.2-1_amd64.deb ...
Unpacking libisl10:amd64 (0.12.2-1) ...
Selecting previously unselected package libcloog-isl4:amd64.
Preparing to unpack .../libcloog-isl4_0.18.2-1_amd64.deb ...
Unpacking libcloog-isl4:amd64 (0.18.2-1) ...
Selecting previously unselected package libgomp1:amd64.
Preparing to unpack .../libgomp1_4.8.4-2ubuntu1~14.04_amd64.deb ...
Unpacking libgomp1:amd64 (4.8.4-2ubuntu1~14.04) ...
Selecting previously unselected package libitm1:amd64.
Preparing to unpack .../libitm1_4.8.4-2ubuntu1~14.04_amd64.deb ...
Unpacking libitm1:amd64 (4.8.4-2ubuntu1~14.04) ...
Selecting previously unselected package libmpfr4:amd64.
Preparing to unpack .../libmpfr4_3.1.2-1_amd64.deb ...
Unpacking libmpfr4:amd64 (3.1.2-1) ...
Selecting previously unselected package libpython3.4:amd64.
Preparing to unpack .../libpython3.4_3.4.3-1ubuntu1~14.04.1_amd64.deb ...
Unpacking libpython3.4:amd64 (3.4.3-1ubuntu1~14.04.1) ...
^C
$ E: Sub-process /usr/bin/dpkg exited unexpectedly
W: Operation was interrupted before it could finish
ERROR:vagga::builder: Error building container "elastic": Command <Command "/usr/bin/apt-get" "install" "-y" "python3-dev" "ca-certificates" "wget" "build-essential" "libxslt1-dev" "libxslt1.1" "libxml2-dev" "libxml2"; environ: {"LANG"="en_US.UTF-8","HOME"="/tmp","PATH"="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games","DEBIAN_FRONTEND"="noninteractive","TERM"="dumb",}; chroot="/vagga/root"; work-dir="/work"> exited with code 100
^C

I'm not certain is in an issue at all, but guess that some locking won't be excess.

**Comment by tailhook** [comment]
Fixed in 806addf. The attempt to build contianers simultaneously fails in current master. While it's possible to wait for the build I don't see good reasons for that for now.
