### ISSUE TITLE
Allow to use !Tar command with local files

### ISSUE THREAD

**Issue by piranna** [tailhook/vagga#81]
Trying to use the `!Tar` command defining a local URL give different errors: when defining the `url` parameter as `out/nocona/initramfs.tar` or `./out/nocona/initramfs.tar` it throw a "bad address" error, with `file:./out/nocona/initramfs.tar` that "bad port spec", and with `file://./out/nocona/initramfs.tar` that "not an http or ftp url". Seems insternally it's being used the `wget` command, so I think this should be override when using a local URL since not always you'll want to use a remote tar file to initialize your filesystem but instead use a local one... Is there any other way to initialize it?

**Comment by tailhook** [comment]
Yes, there is no way to do that currently (except starting a webserver for serving the folder).

**Comment by piranna** [comment]
Could it be possible to implement this? Seems it should be easy... I would do it myself, but I don't know Rust... :-/

**Comment by tailhook** [comment]
Yeah, should be easy. I can help you (or someone) if you want to contribute. Or I can implement the feature for you if you describe your use case (just to satisfy my curiousity and may be we can find a better way).

**Comment by piranna** [comment]
I'm trying to use it in [NodeOS](https://github.com/NodeOS/NodeOS) as an alternative to Docker, since vagga don't needs root permissions. When the image is ready, just by executing `npm start` the system boots from the last generated files, and docker/vagga version is one of them, that's why I want to use the just generated tar file instead of download it from somewhere. I think I could start an ad-hoc web server so it can be downloaded, but seems somewhat hackish... :-/

**Comment by tailhook** [comment]
Yeah, that is somewhat hackish, but is good enough to validate the idea. I've scheduled the feature for vagga 0.4.1, hopefully it will happen in a week or so.

**Comment by piranna** [comment]
Oh cool, thanks! :-D
