### ISSUE TITLE
Allow .. on !Tar command

### ISSUE THREAD

**Issue by piranna** [tailhook/vagga#96]
`!Tar` command now checks if the `url` starts by a dot and consider it's on the current folder instead of trying to download the tarball, but when trying to use a tarball in a parent directory I get the next error:

```
tar: can't open '/work/../nodeos-barebones/out/latest': No such file or directory
ERROR:vagga::builder: Error building container "barebones": step Tar(TarInfo { url: "../nodeos-barebones/out/latest", sha256: None, path: "/", subdir: "" }) failed: Tar exited with status: exited with code 1
ERROR:vagga::wrapper: Error executing _build: Builder exited with code 1
Command <Command "/proc/self/exe" ("vagga_wrapper") "_build" "initramfs"; environ: {"VAGGA_USER_HOME"="/home/piranna","RUST_LOG"="warn","TERM"="xterm",}; uid_map=[UidMap { inside_uid: 0, outside_uid: 1000, count: 1 }, UidMap { inside_uid: 100000, outside_uid: 100000, count: 65536 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1000, count: 1 }, GidMap { inside_gid: 100000, outside_gid: 100000, count: 65536 }]> exited with code 124
```

Seems build process is itself confined and can't access to files outside current folder, isn't it?

**Comment by tailhook** [comment]
> Seems build process is itself confined and can't access to files outside current folder, isn't it?

Sure. This is important part of vagga design. May be fixed by #89

**Comment by piranna** [comment]
> Seems build process is itself confined and can't access to files outside current folder, isn't it?
> 
> Sure. This is important part of vagga design. May be fixed by #89

Make sense. The solution I'm currently doing is to copy the tarballs of previous layers to the current one so they are available in the current folder, maybe I could do a symlink too. I'm trying to think a solution that could vagga implement but don't find anything... :-/

**Comment by tailhook** [comment]
You can do a hardlink. But you can't do a symlink. Symlinks works like paths with files. And containerization (i.e. chroots) is specifically prevents to read things symlinked from outside of the container.

You can also use bind mount `sudo mount --bind ../nodeos-barebones/out ./out`

**Comment by piranna** [comment]
Since I would need to re-create the hardlinks each time since I'm removing the files from their original places, I decided to copy them to their place explicitly.

**Comment by tailhook** [comment]
Probably nothing to do. May be better with #89
